compatibility_date = "2022-05-20"
kv_namespaces = [
  {binding = "POOLS", id = "33da70536f4a4f9b9ea3d5e7fe4e7eed", preview_id = "33da70536f4a4f9b9ea3d5e7fe4e7eed"},
]
r2_buckets = [
  { binding = "SUBGRAPH_POOLS", bucket_name = "subgraph-pools", preview_bucket_name = "subgraph-pools-dev" }
]
main = "src/index.ts"
name = "routing-dev"
node_compat = true
[triggers]
crons = ["0 0 * * *"]

[env.production]
kv_namespaces = [
  {binding = "POOLS", id = "33da70536f4a4f9b9ea3d5e7fe4e7eed"},
]
r2_buckets = [
  { binding = "SUBGRAPH_POOLS", bucket_name = "subgraph-pools", preview_bucket_name = "subgraph-pools-dev" }
]
name = "routing"
[env.production.triggers]
crons = ["0 0 * * *"]

# - AXIOM_TOKEN
# The necessary secrets are:
# - ETH_NODE
# - GOERLI_NODE
# - BSC_NODE
# - BSC_TESTNET_NODE
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
