compatibility_date = "2022-05-20"
kv_namespaces = [
  {binding = "FARMS", id = "31478f36696d4c1294eb412a2adef108", preview_id = "31478f36696d4c1294eb412a2adef108"},
]
main = "src/index.ts"
name = "cadinu-swap"
node_compat = true
[vars]
FORCE_UPDATE_KEY = "force"
KV_CACHE = false
[triggers]
crons = []

[env.production]
kv_namespaces = [
  {binding = "FARMS", id = "31478f36696d4c1294eb412a2adef108"},
]
name = "farms"
node_compat = true
[env.production.vars]
KV_CACHE = true
[env.production.triggers]
crons = ["0 0 * * *", "*/1 * * * *"]

# The necessary secrets are:
# - ETH_NODE
# - GOERLI_NODE
# - BSC_NODE
# - BSC_TESTNET_NODE
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
